name: app_portfolio
description: App Portfolio fo SaifAlmajd
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  loading_animation_widget: ^1.2.0+4
  url_launcher: ^6.1.12
  connectivity_plus: ^4.0.1
  flutter_inappwebview: ^5.8.0



#run flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"
  device_preview: ^1.1.0
  flutter_lints: ^2.0.2



flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/nodata.png
